# Generated by Django 5.2.7 on 2025-10-25 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_course_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Komentar', 'verbose_name_plural': 'Komentar'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Mata Kuliah', 'verbose_name_plural': 'Mata Kuliah'},
        ),
        migrations.AlterModelOptions(
            name='coursecontent',
            options={'verbose_name': 'Konten Matkul', 'verbose_name_plural': 'Konten Matkul'},
        ),
        migrations.AlterModelOptions(
            name='coursemember',
            options={'verbose_name': 'Subscriber Kuliah', 'verbose_name_plural': 'Subscriber Kuliah'},
        ),
        migrations.RenameField(
            model_name='coursemember',
            old_name='joined_at',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='coursemember',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='member',
        ),
        migrations.AlterUniqueTogether(
            name='completion',
            unique_together={('member_id', 'content_id')},
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='content_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.coursecontent', verbose_name='konten'),
        ),
        migrations.AddField(
            model_name='comment',
            name='member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.coursemember', verbose_name='pengguna'),
        ),
        migrations.AddField(
            model_name='completion',
            name='content_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.coursecontent', verbose_name='Lulusan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completion',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='completion',
            name='member_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.coursemember', verbose_name='alumni'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='course_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='core.course', verbose_name='matkul'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.coursecontent', verbose_name='induk'),
        ),
        migrations.AddField(
            model_name='coursemember',
            name='course_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='core.course', verbose_name='matkul'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursemember',
            name='roles',
            field=models.CharField(choices=[('std', 'Siswa'), ('ast', 'Asisten')], default='std', max_length=3, verbose_name='peran'),
        ),
        migrations.AddField(
            model_name='coursemember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coursemember',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='siswa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(verbose_name='komentar'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='-', verbose_name='deskripsi'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='gambar'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nama matkul'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=10000, verbose_name='harga'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='pengajar'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='description',
            field=models.TextField(default='-', verbose_name='deskripsi'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Judul'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL Video'),
        ),
        migrations.RemoveField(
            model_name='coursemember',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursemember',
            name='role',
        ),
        migrations.RemoveField(
            model_name='coursemember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='completion',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='completion',
            name='content',
        ),
        migrations.RemoveField(
            model_name='completion',
            name='member',
        ),
    ]
